---
# Ansible Collections Requirements
collections:
  - name: fortinet.fortios
    version: ">=2.3.0"
  
  - name: servicenow.itsm
    version: ">=2.0.0"
  
  - name: zscaler.zpacloud
    version: ">=2.0.0"
  
  - name: zscaler.ziacloud
    version: ">=2.0.0"
