---
- name: Zscaler Denylist Bulk Management
  hosts: all
  gather_facts: false  # We'll gather facts manually when needed
  
  vars:
    mode: "deny"
    bulk_file_local: "{{ bulk_file | default('deny_urls.txt') }}"
    
    # Execution options
    dry_run: "{{ dry_run_mode | default(false) | bool }}"
    verbose: "{{ verbose_mode | default(false) | bool }}"
  
  tasks:
    # ========================================================================
    # Gather Facts (needed for ansible_date_time)
    # ========================================================================
    
    - name: Gather facts for timestamp
      setup:
      tags: always

    - name: Set dynamic file paths with timestamp
      set_fact:
        bulk_file_remote: "/tmp/zscaler_bulk_urls_{{ ansible_date_time.epoch }}.txt"
        script_path: "/tmp/zscaler_url_automation_{{ ansible_date_time.epoch }}.py"
        log_file_remote: "/tmp/zscaler_automation_{{ ansible_date_time.epoch }}.log"
      tags: always

    # ========================================================================
    # Pre-flight Checks
    # ========================================================================
    
    - name: Display execution banner
      debug:
        msg:
          - "=========================================="
          - "   ZSCALER DENYLIST BULK UPDATE"
          - "=========================================="
          - "Target: {{ inventory_hostname }}"
          - "Mode: {{ mode }}"
          - "Bulk File: {{ bulk_file_local }}"
          - "Dry-Run: {{ dry_run }}"
          - "ZIA Cloud: {{ lookup('env', 'ZIA_CLOUD') | default('zscaler') }}"
          - "Timestamp: {{ ansible_date_time.iso8601 }}"
          - "=========================================="
      tags: always

    - name: Verify Zscaler environment variables are set
      assert:
        that:
          - lookup('env', 'ZIA_USERNAME') | length > 0
          - lookup('env', 'ZIA_PASSWORD') | length > 0
          - lookup('env', 'ZIA_API_KEY') | length > 0
        fail_msg: |
          Missing Zscaler credentials!
          Configure in Semaphore Environment Variables:
          - ZIA_USERNAME
          - ZIA_PASSWORD
          - ZIA_API_KEY
          - ZIA_CLOUD
        success_msg: "✓ Zscaler credentials validated"
      delegate_to: localhost
      run_once: true
      tags: always

    - name: Check if bulk file exists in repository
      stat:
        path: "{{ playbook_dir }}/{{ bulk_file_local }}"
      register: bulk_file_stat
      delegate_to: localhost
      tags: always

    - name: Fail if bulk file not found
      fail:
        msg: |
          Bulk file not found: {{ bulk_file_local }}
          Expected location: {{ playbook_dir }}/{{ bulk_file_local }}
      when: not bulk_file_stat.stat.exists
      tags: always

    - name: Display bulk file information
      debug:
        msg:
          - "File: {{ bulk_file_local }}"
          - "Size: {{ bulk_file_stat.stat.size }} bytes"
          - "Lines: ~{{ (bulk_file_stat.stat.size / 30) | int }}"
      tags: always

    # ========================================================================
    # File Transfer
    # ========================================================================

    - name: Copy bulk URL file to execution host
      copy:
        src: "{{ playbook_dir }}/{{ bulk_file_local }}"
        dest: "{{ bulk_file_remote }}"
        mode: '0644'
      tags: transfer

    - name: Copy Python automation script to execution host
      copy:
        src: "{{ playbook_dir }}/zscaler_url_automation.py"
        dest: "{{ script_path }}"
        mode: '0755'
      tags: transfer

    # ========================================================================
    # Dependencies
    # ========================================================================

    - name: Check Python version
      command: python3 --version
      register: python_version
      changed_when: false
      tags: dependencies

    - name: Display Python version
      debug:
        msg: "{{ python_version.stdout }}"
      tags: dependencies

    - name: Install Python dependencies
      pip:
        name:
          - zscaler-sdk-python
          - requests
        state: present
        executable: pip3
        extra_args: --user
      tags: dependencies

    # ========================================================================
    # Execute Script
    # ========================================================================

    - name: Execute Zscaler bulk update script
      shell: |
        export ZIA_USERNAME="{{ lookup('env', 'ZIA_USERNAME') }}"
        export ZIA_PASSWORD="{{ lookup('env', 'ZIA_PASSWORD') }}"
        export ZIA_API_KEY="{{ lookup('env', 'ZIA_API_KEY') }}"
        export ZIA_CLOUD="{{ lookup('env', 'ZIA_CLOUD') | default('zscaler') }}"
        python3 {{ script_path }} \
          --mode {{ mode }} \
          --bulk-file {{ bulk_file_remote }} \
          {% if dry_run %}--dry-run{% endif %} \
          {% if verbose %}--verbose{% endif %} \
          --log-file {{ log_file_remote }}
      register: script_execution
      changed_when: false
      failed_when: script_execution.rc != 0
      tags: execute

    # ========================================================================
    # Parse Results
    # ========================================================================

    - name: Parse script JSON output
      set_fact:
        update_result: "{{ script_execution.stdout | from_json }}"
      when: script_execution.rc == 0
      tags: results

    - name: Display operation summary
      debug:
        msg:
          - "=========================================="
          - "         OPERATION SUMMARY"
          - "=========================================="
          - "Status: {{ update_result.status | upper }}"
          - "Message: {{ update_result.message | default('N/A') }}"
          - "------------------------------------------"
          - "Existing URLs: {{ update_result.existing_count | default(0) }}"
          - "URLs Added: {{ update_result.added_count | default(0) }}"
          - "Final Count: {{ update_result.final_count | default(0) }}"
          - "=========================================="
      when: update_result is defined
      tags: results

    - name: Display added URLs (successful update)
      debug:
        msg: "Added URLs: {{ update_result.added }}"
      when: 
        - update_result is defined
        - update_result.added_count | default(0) > 0
        - not dry_run
      tags: results

    - name: Display would-be-added URLs (dry-run mode)
      debug:
        msg: "Would add URLs: {{ update_result.would_add }}"
      when:
        - update_result is defined
        - dry_run
        - update_result.would_add_count | default(0) > 0
      tags: results

    - name: Display no-change message
      debug:
        msg: "✓ No changes needed - all URLs already exist in denylist"
      when:
        - update_result is defined
        - update_result.status == "no_change"
      tags: results

    # ========================================================================
    # Error Handling
    # ========================================================================

    - name: Handle errors
      block:
        - name: Display error details
          debug:
            msg:
              - "=========================================="
              - "           ERROR DETECTED"
              - "=========================================="
              - "Status: {{ update_result.status }}"
              - "Message: {{ update_result.message | default('Unknown error') }}"
              - "HTTP Status: {{ update_result.http_status | default('N/A') }}"
              - "=========================================="

        - name: Fail playbook on error
          fail:
            msg: "Script execution failed. Check error details above."
      when:
        - update_result is defined
        - update_result.status == "error"
      tags: results

    # ========================================================================
    # Logging
    # ========================================================================

    - name: Fetch execution log
      slurp:
        src: "{{ log_file_remote }}"
      register: remote_log
      ignore_errors: true
      tags: cleanup

    - name: Display last 30 lines of log
      debug:
        msg: "{{ (remote_log.content | b64decode).split('\n')[-30:] }}"
      when: remote_log is succeeded
      tags: cleanup

    # ========================================================================
    # Cleanup
    # ========================================================================

    - name: Remove temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ bulk_file_remote }}"
        - "{{ script_path }}"
        - "{{ log_file_remote }}"
      tags: cleanup

    # ========================================================================
    # Final Summary
    # ========================================================================

    - name: Generate execution summary
      set_fact:
        execution_summary:
          timestamp: "{{ ansible_date_time.iso8601 }}"
          operation: "{{ mode }}list_bulk_update"
          status: "{{ update_result.status | default('unknown') }}"
          dry_run: "{{ dry_run }}"
          urls_processed: "{{ update_result.added_count | default(0) }}"
          final_count: "{{ update_result.final_count | default(0) }}"
          zia_cloud: "{{ lookup('env', 'ZIA_CLOUD') | default('zscaler') }}"
      when: update_result is defined
      tags: summary

    - name: Display execution summary
      debug:
        msg: "{{ execution_summary | to_nice_yaml }}"
      when: execution_summary is defined
      tags: summary

    - name: Playbook completed successfully
      debug:
        msg: "✓ Playbook execution complete"
      tags: always
