---
- name: Zscaler Denylist Bulk Management
  hosts: all
  gather_facts: false
  
  vars:
    mode: "deny"
    
    # Support both file-based and variable-based input
    bulk_file_local: "{{ bulk_file | default('') }}"
    url_list: "{{ urls | default([]) }}"
    
    # Execution options
    dry_run: "{{ dry_run_mode | default(false) | bool }}"
    verbose: "{{ verbose_mode | default(false) | bool }}"
  
  tasks:
    # ========================================================================
    # Gather Facts
    # ========================================================================
    
    - name: Gather facts for timestamp
      setup:
      tags: always

    - name: Set dynamic file paths
      set_fact:
        bulk_file_remote: "/tmp/zscaler_bulk_urls_{{ ansible_date_time.epoch }}.txt"
        script_path: "/tmp/zscaler_url_automation_{{ ansible_date_time.epoch }}.py"
        log_file_remote: "/tmp/zscaler_automation_{{ ansible_date_time.epoch }}.log"
      tags: always

    # ========================================================================
    # Pre-flight Checks
    # ========================================================================
    
    - name: Display execution banner
      debug:
        msg:
          - "=========================================="
          - "   ZSCALER DENYLIST BULK UPDATE"
          - "=========================================="
          - "Mode: {{ mode }}"
          - "Dry-Run: {{ dry_run }}"
          - "ZIA Cloud: {{ lookup('env', 'ZIA_CLOUD') | default('zscaler') }}"
          - "Input Method: {{ 'File' if bulk_file_local else 'Variables' }}"
          - "=========================================="
      tags: always

    - name: Verify Zscaler environment variables
      assert:
        that:
          - lookup('env', 'ZIA_USERNAME') | length > 0
          - lookup('env', 'ZIA_PASSWORD') | length > 0
          - lookup('env', 'ZIA_API_KEY') | length > 0
        fail_msg: "Missing Zscaler credentials in Environment Variables"
        success_msg: "✓ Zscaler credentials validated"
      delegate_to: localhost
      run_once: true
      tags: always

    # ========================================================================
    # Input Validation - File or Variable?
    # ========================================================================

    - name: Check input method
      set_fact:
        using_file: "{{ bulk_file_local | length > 0 }}"
        using_vars: "{{ url_list | length > 0 }}"
      tags: always

    - name: Fail if no input provided
      fail:
        msg: |
          No URLs provided!
          
          Provide URLs via either:
          1. Extra variable 'urls' (list)
          2. Extra variable 'bulk_file' (filename)
          
          Example with variables:
          urls:
            - malicious1.com
            - malicious2.com
            - malicious3.com
      when: not using_file and not using_vars
      tags: always

    # ========================================================================
    # Process File-Based Input
    # ========================================================================

    - name: Process file-based input
      block:
        - name: Check if bulk file exists
          stat:
            path: "{{ playbook_dir }}/{{ bulk_file_local }}"
          register: bulk_file_stat
          delegate_to: localhost

        - name: Fail if file not found
          fail:
            msg: "Bulk file not found: {{ playbook_dir }}/{{ bulk_file_local }}"
          when: not bulk_file_stat.stat.exists

        - name: Copy bulk file to remote
          copy:
            src: "{{ playbook_dir }}/{{ bulk_file_local }}"
            dest: "{{ bulk_file_remote }}"
            mode: '0644'
          
      when: using_file
      tags: transfer

    # ========================================================================
    # Process Variable-Based Input
    # ========================================================================

    - name: Process variable-based input
      block:
        - name: Display URLs from variables
          debug:
            msg: "Processing {{ url_list | length }} URLs from extra variables"

        - name: Create temporary file from URL list
          copy:
            content: "{{ url_list | join('\n') }}\n"
            dest: "{{ bulk_file_remote }}"
            mode: '0644'

        - name: Display URLs to be processed
          debug:
            msg: "{{ url_list }}"
          
      when: using_vars
      tags: transfer

    # ========================================================================
    # Copy Script
    # ========================================================================

    - name: Copy Python automation script
      copy:
        src: "{{ playbook_dir }}/zscaler_url_automation.py"
        dest: "{{ script_path }}"
        mode: '0755'
      tags: transfer

    # ========================================================================
    # Dependencies
    # ========================================================================

    - name: Check Python version
      command: python3 --version
      register: python_version
      changed_when: false
      tags: dependencies

    - name: Display Python version
      debug:
        msg: "{{ python_version.stdout }}"
      tags: dependencies

    - name: Install Python dependencies
      pip:
        name:
          - zscaler-sdk-python
          - requests
        state: present
        executable: pip3
        extra_args: --user
      tags: dependencies

    # ========================================================================
    # Execute Script
    # ========================================================================

    - name: Execute Zscaler bulk update script
      shell: |
        export ZIA_USERNAME="{{ lookup('env', 'ZIA_USERNAME') }}"
        export ZIA_PASSWORD="{{ lookup('env', 'ZIA_PASSWORD') }}"
        export ZIA_API_KEY="{{ lookup('env', 'ZIA_API_KEY') }}"
        export ZIA_CLOUD="{{ lookup('env', 'ZIA_CLOUD') | default('zscaler') }}"
        python3 {{ script_path }} \
          --mode {{ mode }} \
          --bulk-file {{ bulk_file_remote }} \
          {% if dry_run %}--dry-run{% endif %} \
          {% if verbose %}--verbose{% endif %} \
          --log-file {{ log_file_remote }}
      register: script_execution
      changed_when: false
      failed_when: script_execution.rc != 0
      tags: execute

    # ========================================================================
    # Parse Results
    # ========================================================================

    - name: Parse script JSON output
      set_fact:
        update_result: "{{ script_execution.stdout | from_json }}"
      when: script_execution.rc == 0
      tags: results

    - name: Display operation summary
      debug:
        msg:
          - "=========================================="
          - "         OPERATION SUMMARY"
          - "=========================================="
          - "Status: {{ update_result.status | upper }}"
          - "Message: {{ update_result.message | default('N/A') }}"
          - "------------------------------------------"
          - "Existing URLs: {{ update_result.existing_count | default(0) }}"
          - "URLs Added: {{ update_result.added_count | default(0) }}"
          - "Final Count: {{ update_result.final_count | default(0) }}"
          - "=========================================="
      when: update_result is defined
      tags: results

    - name: Display added URLs
      debug:
        msg: "Added: {{ update_result.added }}"
      when: 
        - update_result is defined
        - update_result.added_count | default(0) > 0
        - not dry_run
      tags: results

    - name: Display would-be-added URLs (dry-run)
      debug:
        msg: "Would add: {{ update_result.would_add }}"
      when:
        - update_result is defined
        - dry_run
        - update_result.would_add_count | default(0) > 0
      tags: results

    - name: Display no-change message
      debug:
        msg: "✓ No changes needed - all URLs already exist"
      when:
        - update_result is defined
        - update_result.status == "no_change"
      tags: results

    # ========================================================================
    # Error Handling
    # ========================================================================

    - name: Handle errors
      block:
        - name: Display error details
          debug:
            msg:
              - "=========================================="
              - "           ERROR DETECTED"
              - "=========================================="
              - "Status: {{ update_result.status }}"
              - "Message: {{ update_result.message | default('Unknown error') }}"
              - "HTTP Status: {{ update_result.http_status | default('N/A') }}"
              - "=========================================="

        - name: Fail playbook
          fail:
            msg: "Script execution failed"
      when:
        - update_result is defined
        - update_result.status == "error"
      tags: results

    # ========================================================================
    # Cleanup
    # ========================================================================

    - name: Remove temporary files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ bulk_file_remote }}"
        - "{{ script_path }}"
        - "{{ log_file_remote }}"
      tags: cleanup

    # ========================================================================
    # Summary
    # ========================================================================

    - name: Generate execution summary
      set_fact:
        execution_summary:
          timestamp: "{{ ansible_date_time.iso8601 }}"
          operation: "{{ mode }}list_bulk_update"
          status: "{{ update_result.status | default('unknown') }}"
          dry_run: "{{ dry_run }}"
          urls_processed: "{{ update_result.added_count | default(0) }}"
          final_count: "{{ update_result.final_count | default(0) }}"
      when: update_result is defined
      tags: summary

    - name: Display execution summary
      debug:
        msg: "{{ execution_summary | to_nice_yaml }}"
      when: execution_summary is defined
      tags: summary

    - name: Playbook completed
      debug:
        msg: "✓ Execution complete"
      tags: always
