 name: Zscaler Denylist Bulk Management
  hosts: all
  gather_facts: false
  
  vars:
    mode: "deny"
    bulk_file_local: "{{ bulk_file }}"
    dry_run: "{{ dry_run_mode | default(true) | bool }}"
  
  tasks:
    - name: Gather facts
      setup:

    - name: Set dynamic paths
      set_fact:
        bulk_file_remote: "/tmp/zscaler_bulk_urls_{{ ansible_date_time.epoch }}.txt"
        script_path: "/tmp/zscaler_url_automation_{{ ansible_date_time.epoch }}.py"
        log_file_remote: "/tmp/zscaler_automation_{{ ansible_date_time.epoch }}.log"

    - name: Display execution banner
      debug:
        msg:
          - "=========================================="
          - "   ZSCALER DENYLIST BULK UPDATE"
          - "=========================================="
          - "Mode: {{ mode }}"
          - "Bulk File: {{ bulk_file_local }}"
          - "Dry-Run: {{ dry_run }}"
          - "=========================================="

    - name: Verify Zscaler credentials
      assert:
        that:
          - lookup('env', 'ZIA_USERNAME') | length > 0
          - lookup('env', 'ZIA_PASSWORD') | length > 0
          - lookup('env', 'ZIA_API_KEY') | length > 0
        fail_msg: "Missing Zscaler credentials"
      delegate_to: localhost
      run_once: true

    - name: Check if bulk file exists
      stat:
        path: "{{ playbook_dir }}/{{ bulk_file_local }}"
      register: bulk_file_stat
      delegate_to: localhost

    - name: Show file path
      debug:
        msg: "Looking for: {{ playbook_dir }}/{{ bulk_file_local }}"

    - name: Fail if file not found
      fail:
        msg: "File not found: {{ playbook_dir }}/{{ bulk_file_local }}"
      when: not bulk_file_stat.stat.exists

    - name: Copy bulk file
      copy:
        src: "{{ playbook_dir }}/{{ bulk_file_local }}"
        dest: "{{ bulk_file_remote }}"
        mode: '0644'

    - name: Copy Python script
      copy:
        src: "{{ playbook_dir }}/zscaler_url_automation.py"
        dest: "{{ script_path }}"
        mode: '0755'

    - name: Install dependencies
      pip:
        name:
          - zscaler-sdk-python
          - requests
        state: present
        executable: pip3
        extra_args: --user

    - name: Execute Zscaler script
      shell: |
        export ZIA_USERNAME="{{ lookup('env', 'ZIA_USERNAME') }}"
        export ZIA_PASSWORD="{{ lookup('env', 'ZIA_PASSWORD') }}"
        export ZIA_API_KEY="{{ lookup('env', 'ZIA_API_KEY') }}"
        export ZIA_CLOUD="{{ lookup('env', 'ZIA_CLOUD') | default('zscaler') }}"
        python3 {{ script_path }} \
          --mode {{ mode }} \
          --bulk-file {{ bulk_file_remote }} \
          {% if dry_run %}--dry-run{% endif %} \
          --log-file {{ log_file_remote }}
      register: script_execution
      changed_when: false
      failed_when: script_execution.rc != 0

    - name: Parse result
      set_fact:
        update_result: "{{ script_execution.stdout | from_json }}"
      when: script_execution.rc == 0

    - name: Display summary
      debug:
        msg:
          - "=========================================="
          - "Status: {{ update_result.status | upper }}"
          - "Message: {{ update_result.message | default('N/A') }}"
          - "Existing URLs: {{ update_result.existing_count | default(0) }}"
          - "URLs Added: {{ update_result.added_count | default(0) }}"
          - "Final Count: {{ update_result.final_count | default(0) }}"
          - "=========================================="
      when: update_result is defined

    - name: Show added URLs
      debug:
        msg: "Added: {{ update_result.added }}"
      when: 
        - update_result is defined
        - update_result.added_count | default(0) > 0
        - not dry_run

    - name: Show would-add URLs (dry-run)
      debug:
        msg: "Would add: {{ update_result.would_add }}"
      when:
        - update_result is defined
        - dry_run
        - update_result.would_add_count | default(0) > 0

    - name: Handle errors
      fail:
        msg: "Error: {{ update_result.message }}"
      when:
        - update_result is defined
        - update_result.status == "error"

    - name: Cleanup
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ bulk_file_remote }}"
        - "{{ script_path }}"
        - "{{ log_file_remote }}"

    - name: Execution complete
      debug:
        msg: "✓ Playbook complete"
EOF
