---
- name: Zscaler Denylist Bulk Management
  hosts: all
  gather_facts: false
  
  vars:
    mode: "deny"
    bulk_file_local: "{{ bulk_file | default('deny_urls.txt') }}"
    dry_run: "{{ dry_run_mode | default(true) | bool }}"
  
  tasks:
    - name: Gather facts
      setup:

    - name: Set dynamic paths
      set_fact:
        bulk_file_remote: "/tmp/zscaler_bulk_{{ ansible_date_time.epoch }}.txt"
        script_path: "/tmp/zscaler_script_{{ ansible_date_time.epoch }}.py"
        log_file: "/tmp/zscaler_log_{{ ansible_date_time.epoch }}.log"

    - name: Display banner
      debug:
        msg:
          - "=========================================="
          - "File: {{ bulk_file_local }}"
          - "Dry-Run: {{ dry_run }}"
          - "=========================================="

    - name: Verify credentials
      assert:
        that:
          - lookup('env', 'ZIA_USERNAME') | length > 0
          - lookup('env', 'ZIA_PASSWORD') | length > 0
          - lookup('env', 'ZIA_API_KEY') | length > 0
        fail_msg: "Missing credentials"
      delegate_to: localhost
      run_once: true

    - name: Check file exists
      stat:
        path: "{{ playbook_dir }}/{{ bulk_file_local }}"
      register: file_check
      delegate_to: localhost

    - name: Fail if not found
      fail:
        msg: "File not found: {{ bulk_file_local }}"
      when: not file_check.stat.exists

    - name: Copy files
      copy:
        src: "{{ playbook_dir }}/{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop:
        - { src: "{{ bulk_file_local }}", dest: "{{ bulk_file_remote }}", mode: '0644' }
        - { src: "zscaler_url_automation.py", dest: "{{ script_path }}", mode: '0755' }

    - name: Install dependencies
      pip:
        name:
          - zscaler-sdk-python
          - requests
        state: present
        executable: pip3
        extra_args: --user

    - name: Run script
      shell: |
        export ZIA_USERNAME="{{ lookup('env', 'ZIA_USERNAME') }}"
        export ZIA_PASSWORD="{{ lookup('env', 'ZIA_PASSWORD') }}"
        export ZIA_API_KEY="{{ lookup('env', 'ZIA_API_KEY') }}"
        export ZIA_CLOUD="{{ lookup('env', 'ZIA_CLOUD') | default('zscaler') }}"
        python3 {{ script_path }} \
          --mode {{ mode }} \
          --bulk-file {{ bulk_file_remote }} \
          {% if dry_run %}--dry-run{% endif %} \
          --log-file {{ log_file }}
      register: result
      failed_when: false
      changed_when: false

    - name: Show what script returned
      debug:
        msg:
          - "Return code: {{ result.rc }}"
          - "Output: {{ result.stdout }}"
          - "Errors: {{ result.stderr }}"

    - name: Try to parse JSON
      set_fact:
        parsed: "{{ result.stdout | from_json }}"
      when: result.rc == 0 and result.stdout | length > 0
      ignore_errors: true

    - name: Show result if parsed
      debug:
        msg:
          - "Status: {{ parsed.status }}"
          - "Added: {{ parsed.added_count | default(0) }}"
      when: parsed is defined

    - name: Cleanup
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ bulk_file_remote }}"
        - "{{ script_path }}"
        - "{{ log_file }}"

    - name: Done
      debug:
        msg: "Complete"
